# Generated by Django 4.1.5 on 2023-02-01 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="vote",
            field=models.ManyToManyField(
                related_name="vote_post",
                to=settings.AUTH_USER_MODEL,
                verbose_name="추천수",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writer_post",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="community.post",
                verbose_name="작성글",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="community.answer",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="vote",
            field=models.ManyToManyField(
                related_name="vote_comment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="추천수",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writer_comment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.post"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="vote",
            field=models.ManyToManyField(
                related_name="vote_answer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="추천수",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writer_answer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
    ]
