# Generated by Django 4.1.5 on 2023-02-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='url',
        ),
    ]
