# Generated by Django 4.1.5 on 2023-02-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_remove_volunteer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='title',
            field=models.CharField(max_length=30, verbose_name='제목'),
        ),
    ]
